project_id = "qvsrhfzdkjygjuwmfwmh"

[functions.update-club-status]
verify_jwt = false

[functions.create-club]
verify_jwt = false

[functions.send-announcement-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-event-update-email]
verify_jwt = false

[functions.create-student-account]
verify_jwt = false

[functions.create-mentor-account]
verify_jwt = false

[functions.student-forgot-password]
verify_jwt = false

[functions.send-new-event-email]
verify_jwt = false
